# Generated by Django 2.1.15 on 2023-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_shelter',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
    ]
