# Generated by Django 2.1.15 on 2023-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0002_auto_20231021_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_shelter',
            name='abandonment_reason',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_shelter',
            name='favorite_food',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_shelter',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_shelter',
            name='picture',
            field=models.ImageField(default='Unknown', upload_to='animal_pictures/'),
            preserve_default=False,
        ),
    ]
