# Generated by Django 2.1.15 on 2023-10-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0003_auto_20231021_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal_Shelter',
            new_name='AnimalShelter',
        ),
    ]
