# Generated by Django 2.1.15 on 2023-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0006_adopter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
