# Generated by Django 2.1.15 on 2023-10-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0008_remove_adoptionpolicy_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalshelter',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='animalshelter',
            name='age',
            field=models.DateTimeField(default='Unknown', verbose_name='Age'),
            preserve_default=False,
        ),
    ]
