# Generated by Django 2.1.15 on 2023-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0009_auto_20231021_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalshelter',
            name='age',
        ),
        migrations.AddField(
            model_name='animalshelter',
            name='date_of_birth',
            field=models.DateTimeField(default='Unknown', verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
